import { motion } from "framer-motion";
import { useState } from "react";
import { fiveBiggestDecisions } from "../engine/endings";
import { beliefRevealRows } from "../engine/postmortemSupport";
import type { GameState } from "../engine/types";
import { useGame } from "../store/useGame";

function LineChart({ game }: { game: GameState }) {
  const points=game.history; const maxCash=Math.max(1,...points.map((point)=>Math.max(0,point.cash))); const maxMrr=Math.max(1,...points.map((point)=>point.mrr)); const x=(week:number)=>55+(week-1)/103*890; const yCash=(value:number)=>330-Math.max(0,value)/maxCash*250; const yMrr=(value:number)=>330-value/maxMrr*250; const cashPath=points.map((point,index)=>`${index?"L":"M"}${x(point.week)} ${yCash(point.cash)}`).join(" "); const mrrPath=points.map((point,index)=>`${index?"L":"M"}${x(point.week)} ${yMrr(point.mrr)}`).join(" "); const decisions=fiveBiggestDecisions(game.decisionLog);
  return <svg className="pm-chart" viewBox="0 0 1000 390" role="img" aria-label="Cash and MRR across the run with five major decisions"><path d="M55 40v290h890" stroke="#8f8a81" strokeWidth="2" fill="none"/><path d={cashPath} fill="none" stroke="#e1523d" strokeWidth="5" strokeLinecap="round"/><path d={mrrPath} fill="none" stroke="#2f7a5e" strokeWidth="5" strokeLinecap="round"/><text x="55" y="25">CASH</text><text x="125" y="25" fill="#2f7a5e">MRR</text>{decisions.map((decision,index)=>{const point=[...points].reverse().find((item)=>item.week<=decision.week)??points[0];const px=x(decision.week),py=yCash(point.cash);return <g key={decision.id}><circle cx={px} cy={py} r="8" fill="#22201d"/><path d={`M${px} ${py-8}v${-28-index%2*22}`} stroke="#22201d"/><text x={px} y={py-44-index%2*22} textAnchor="middle">W{decision.week}</text></g>;})}<text x="55" y="365">W1</text><text x="920" y="365">W104</text></svg>;
}

function newSeed(){const values=new Uint32Array(1);crypto.getRandomValues(values);return values[0]||7;}
export function PostMortem({ game }: { game: GameState }) { const data=game.postMortem; const runAgain=useGame((s)=>s.runAgain),start=useGame((s)=>s.start),abandon=useGame((s)=>s.abandon);const[copied,setCopied]=useState(false);if(!data)return null;const rows=beliefRevealRows(game);const copy=async()=>{await navigator.clipboard.writeText(data.shareText);setCopied(true);window.setTimeout(()=>setCopied(false),1800);};return <main className="postmortem"><motion.header initial={{opacity:0,y:25}} animate={{opacity:1,y:0}}><span className="eyebrow">POST-MORTEM · SEED {game.seed}</span><i>{data.grade}</i><h1>{data.title}</h1><p>{data.feedback}</p></motion.header><motion.section className="reveal-block" initial={{opacity:0,y:25}} animate={{opacity:1,y:0}} transition={{delay:.35}}><span className="eyebrow">01 · WHAT WAS TRUE</span><div className="truth-table"><div><span>DIMENSION</span><span>YOU COMMITTED</span><span>THE MARKET</span></div>{rows.map((row)=><article key={row.key} className={row.correct?"correct":"wrong"}><strong>{row.label}</strong><span>{row.believed}</span><span>{row.truth}<b>{row.correct?"RIGHT":"WRONG"}</b></span></article>)}</div></motion.section><motion.section className="reveal-block could-know" initial={{opacity:0,y:25}} animate={{opacity:1,y:0}} transition={{delay:.7}}><span className="eyebrow">02 · THE WEEK YOU COULD HAVE KNOWN</span><strong>{data.couldKnowWeek?`WEEK ${data.couldKnowWeek}`:"NO CLEAN WEEK"}</strong><p>{data.couldKnowText}</p></motion.section><motion.section className="reveal-block" initial={{opacity:0,y:25}} animate={{opacity:1,y:0}} transition={{delay:1}}><span className="eyebrow">03 · THE SHAPE OF THE RUN</span><LineChart game={game}/></motion.section><motion.section className="reveal-block counterfactual" initial={{opacity:0,y:25}} animate={{opacity:1,y:0}} transition={{delay:1.25}}><span className="eyebrow">04 · LARGEST COUNTERFACTUAL SWING</span><p>{data.counterfactual}</p></motion.section><motion.section className="pm-final" initial={{opacity:0}} animate={{opacity:1}} transition={{delay:1.5}}><div><span className="eyebrow">05 · VERDICT</span><h2>GRADE {data.grade}</h2><p>{data.feedback}</p></div><div className="share-box"><pre>{data.shareText}</pre><button onClick={copy}>{copied?"Copied":"Copy summary"}</button></div><div className="pm-actions"><button className="primary" onClick={runAgain}>Run this market again <span>→</span></button><button className="secondary" onClick={()=>start(newSeed())}>New market</button><button className="secondary" onClick={abandon}>Title</button></div></motion.section></main>; }
