import type { ReactNode } from "react";

function activate(event: React.KeyboardEvent<SVGGElement>, action: () => void) { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); action(); } }
export function RoomControl({ label, x, y, badge, children, onClick }: { label: string; x: number; y: number; badge?: string | number; children: ReactNode; onClick: () => void }) {
  return <g className="room-control" transform={`translate(${x} ${y})`} role="button" tabIndex={0} aria-label={label} onClick={onClick} onKeyDown={(event) => activate(event, onClick)}>{children}<g className="object-label"><rect x="-70" y="25" width="140" height="32" rx="16"/><text x="0" y="46" textAnchor="middle">{label}</text></g>{badge !== undefined && <g className="object-badge"><circle cx="32" cy="-32" r="18"/><text x="32" y="-27" textAnchor="middle">{badge}</text></g>}</g>;
}
export const LaptopObject = ({ onClick, pulse }: { onClick: () => void; pulse: boolean }) => <RoomControl label="Metrics" x={700} y={565} onClick={onClick} badge={pulse ? "!" : undefined}><g className={pulse ? "pulse-object" : ""}><rect x="-55" y="-50" width="110" height="65" rx="5" fill="#4a5259" stroke="#22201d" strokeWidth="5"/><rect x="-43" y="-39" width="86" height="42" fill="#b9d4d1"/><path d="M-70 17h140l-18 12h-104z" fill="#727a80" stroke="#22201d" strokeWidth="4"/></g></RoomControl>;
export const NotebookObject = ({ onClick, badge }: { onClick: () => void; badge: number }) => <RoomControl label="Notebook" x={505} y={590} onClick={onClick} badge={badge || undefined}><g transform="rotate(-7)"><rect x="-44" y="-30" width="88" height="60" rx="4" fill="#e7dfd2" stroke="#22201d" strokeWidth="5"/><path d="M-30 -13h56M-30 0h45M-30 13h50" stroke="#8f8a81" strokeWidth="3"/></g></RoomControl>;
export const PhoneObject = ({ onClick, badge }: { onClick: () => void; badge: number }) => <RoomControl label="Inbox" x={850} y={588} onClick={onClick} badge={badge || undefined}><rect x="-25" y="-42" width="50" height="84" rx="9" fill="#22201d"/><rect x="-18" y="-31" width="36" height="56" rx="3" fill="#8db5b2"/></RoomControl>;
export const WhiteboardObject = ({ onClick, count }: { onClick: () => void; count: number }) => <RoomControl label="Roadmap" x={1080} y={345} onClick={onClick}><rect x="-150" y="-100" width="300" height="200" rx="5" fill="#f4f0e9" stroke="#22201d" strokeWidth="7"/><path d="M-110 -50h150M-110 -15h210M-110 20h120" stroke="#8ba5a2" strokeWidth="6"/><text x="75" y="65" className="board-count">{count}/8</text></RoomControl>;
export const DoorObject = ({ onClick, knock }: { onClick: () => void; knock: boolean }) => <RoomControl label="Team" x={1480} y={480} onClick={onClick} badge={knock ? "·" : undefined}><rect x="-75" y="-180" width="150" height="360" fill="#9b7a50" stroke="#22201d" strokeWidth="8"/><circle cx="45" cy="5" r="9" fill="#f2b857"/></RoomControl>;
export const FilingObject = ({ onClick, glow }: { onClick: () => void; glow: boolean }) => <RoomControl label="Capital" x={1320} y={640} onClick={onClick} badge={glow ? "$" : undefined}><g className={glow ? "filing-glow" : ""}><rect x="-60" y="-100" width="120" height="200" fill="#687178" stroke="#22201d" strokeWidth="6"/><path d="M-60 -35h120M-60 30h120" stroke="#22201d" strokeWidth="5"/><path d="M-18 -67h36M-18 -2h36M-18 63h36" stroke="#d2d6d5" strokeWidth="5"/></g></RoomControl>;
