import type { Background, GameState } from "./types";

export function createGame(input: { name: string; email: string; background: Background }): GameState {
  return {
    version: 1,
    saveId: crypto.randomUUID(),
    loggedIn: true,
    founderName: input.name,
    email: input.email,
    background: input.background,
    week: 1,
    year: 2027,
    personalCash: 2000,
    network: 8,
    reputation: 4,
    founderEnergy: 100,
    ideaResearch: 0,
    ideaName: "Relaydesk",
    companyFormed: false,
    companyName: "",
    companyCash: 0,
    productProgress: 0,
    productQuality: input.background === "Design" ? 50 : 35,
    productLaunched: false,
    price: 149,
    customers: 0,
    salesPipeline: 0,
    marketing: 0,
    morale: 82,
    office: "Apartment",
    employees: [],
    snapshots: [],
    history: [{ id: "career-start", week: 1, category: "Founder", title: "A new founder career begins", detail: `${input.name} starts with $2,000, one laptop, and a small network.` }],
    ledger: [],
    pendingEvent: null,
    distressWeeks: 0,
    gameOver: false,
    selectedEmployeeId: null,
  };
}
